### ISSUE TITLE
Browser issue (Safari)

### ISSUE THREAD

**Issue by Quintman** [yale-web-technologies/mirador-annotations#71] opened 2016-04-29 15:46 UTC
I know Chrome is the preferred browser. Just FYI: Safari (on Mac OS 10.11.4) does not show annotation drawings.

**Comment by gigamorph** [comment] 2016-04-29 17:54
I cannot reproduce the situation. Sometimes it takes rather a long time to load. Could you try waiting a bit before going into the "view annotation" mode?

**Comment by gigamorph** [comment] 2016-05-20 20:04
Re-created the issue at
https://github.com/yale-web-technologies/mirador-project/issues/4

Closing this one.

**Closed** 2016-05-20 20:05 UTC
Labels: bug, invalid
