### ISSUE TITLE
Mouse over annotation only highlighting on line edge

### ISSUE THREAD

**Issue by lecmaj** [yale-web-technologies/mirador-annotations#57] opened 2016-04-08 15:53 UTC

**Comment by lecmaj** [comment] 2016-04-08 15:53
Seong mention that the case is because the box is really not closed, it is important to close the boxes with free form.

**Comment by gigamorph** [comment] 2016-05-20 20:45
Duplicate of https://github.com/yale-web-technologies/mirador-project/issues/6

**Closed by gigamorph** 2016-05-20 20:45 UTC
Labels: bug, duplicate
